test-data: ENC[AES256_GCM,data:5RNSDcS9MeyH2UqsTAg=,iv:yOAO2klupD1SwBhTho0yJcZq5qSVYk5GF3UnzrJvFWo=,tag:blRPLQ+X3PbSX+EnZSWGVQ==,type:str]
users:
    sparks:
        passwd: ENC[AES256_GCM,data:eTK54WiBZVRqt/yCt0i2EGTzvzC0KLrECkWDZqcK3qjFMb5BOWkune9uMP6aPlwrkUpLIFKE/GzXO0lAXGgUhcp7aJ2XOSP9VQ==,iv:gYwQGjIqpDJh4aCfcnzyJ7DdbTYb/ApnKZyewX2lorM=,tag:bkGsoP45T2iwVwyVGhHgKg==,type:str]
networking:
    wireless.conf: ENC[AES256_GCM,data:KzCOEvUEp+GVAjSvK5NfJdkXTf7kZxmXmdmBDhFlr+GnmS+HwK9Gb+G0zL5lRiCEj2Y5xxV+rN7lTeRNRPsvewhcpuLK97pkL9JSEkQFrpR3wxiS1PVTPhYU5i/CKs1eU57j0vKTUIR68q/8VIwSVQnDiQqa3/WcHp4ZNL4ysvYEQB4gzCRkKWD01lEM7JWMOxM8q2xCaZJHEHQdzLWVULl/PnYI+VK7arFx/NF6n54wP97ePAOFzMz8tA2dkY0UznihZhp4ZA==,iv:Ujbwb3FERNxvleNcjs7H8/Iofmu3SEht3lfMY5cX0O0=,tag:Q5SxwzvBueZ09oZHHKL6cw==,type:str]
k3s:
    node-token: ENC[AES256_GCM,data:s6woz0eAqI5RnVI+xG0QY2seiAx8xEo1jeM71Hr9l0z8h1w+0oT0djBgQbE1AzKywAH0md+/ggy9aagXpdKVW8LWyHTBr1KLwfzCB/WJ3UCO4j81Yimc8ZA39ows0kmv405Qy6rtlY9STYzy,iv:hb+XhV7ZNRaOPRWLbq+I7IAETnYbzvbOQe5qVujBJ2w=,tag:xNHbfc77C7K9ccGR/i9/Iw==,type:str]
sops:
    age:
        - recipient: age1jayaggqedpe7djyjpk0a74xxc2vlqzumeah39f548rnkjse76syst7t4pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUkFVMVRQQ0xmbldkSitj
            ekJPT1pUaU0xMnJId0tvRnlLOFNucHlBQkRVCnBIVWVRbFVsQ0x5SmovYUpieVpa
            dmNtNTBGdHlvNExWdlRqdVIrNVdUNjgKLS0tIHlxSm0yV2NWQVpKakpFQzdrZmZ3
            aWNVZDZ6YkxIYTgyOTJYMFAyMDZEMDQKQubPTB0o92ABFsq1c+Gj2Eitc8n0Febu
            CpBc4jfbQs3PWVbfEzdTYXOctA+eX5UjT1RNBJLBjyqb36FJ5c5Tvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p6y752pv3ze0a82lec5lyv5n20xex3ennpscgj8ueu7tecqpfd5s4wqe2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMGZOYStKK1JnN1VqVzhM
            amtsRjdTRVMwOURhYVhRRTlCa0EvRFpmTnpFCjcxVzF3SjNBck9XdktYUkltYklJ
            dGFVcUh3NTNTRlNNazF1SGNDVWJGaDgKLS0tIHJ1Y3gvVzY5cWxDUCtTdW5Tb0p5
            enNMdEFpa0pIN0gyYXUyV0V3YXdKenMKYtLH8lK7+9+Jp03D8XdE7nc9PzPrreG7
            Nq1VWrnFHtGndaY5cvY10yfNWAQanU64hvOlJJ4AbWVH6rn7TTatvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17auaf780ad2m0jm5e348c8fpjeak3795jw8dgnmj6yk02whykdyq5eh9ps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleXFOUXgvblhDNnlEbnBN
            YXMxakc5NnVxMFBvYzZxSDdZbXZzTk9ISTNzCmVaaDhZZzE5ZC83RG9iWkFnSmFC
            UWp6ZVRWYi9OZjNyN2d0Slo5bncraW8KLS0tIDhqRjM3Rk1XeUtlckovb2hMaHd6
            VjRENm9UaFhydExuRG1BeUxBeDNsd0UKpZplJJN1M2G1SBsasp7htbdhpEK2rVhU
            pHtlpdppv7ffChvx01pN/HKuzS7xWdaGK3J2wBRAQgdTHyDOYC7LfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T20:16:23Z"
    mac: ENC[AES256_GCM,data:t4Tl5khdaybpdtrme+4edVMai6NBwAPstgrjqWpS9pqBYIPbnX1qwHMRtu5sZ3QJzKRM4s9vIGzw8dErpMvhPE+SPVqjbSbxURd1NbPQ/NFlcclKSDU8ZA7lBoAPqzm3He/Nt6HLCCtSNXw4IsJfQtJ13HsqxKa/Jrsuk+MCwOY=,iv:3GJaqxRJ0iII+SvlpiPyw2Xi9gmUrhB41zK4VlkKEmE=,tag:TZ6h+YUpLOAqPk+Xq1k1cw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
